### ISSUE TITLE
Step 2 of Authentication has been blocked

### ISSUE THREAD

**Issue by buzzbros2002** [gitagogaming/Youtube-TouchPortal-Plugin#15]
This app is blocked

This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.

-------

This is what comes up now.

**Comment by gitagogaming** [comment]
I’m sorry about this error, Unfortunately the app I had made exceeded 100 users and Google has begun to block new users. I have created a temporary work around until I can get in contact with Google/Youtube again which involves you creating your own Developer account.. Its fairly easy to do and I have a video on how to do it in the TouchPortal Discord.. Feel free to join message me if you have any issues. https://discord.gg/touchportal
Thanks Gitago
